witmotion:
  ros__parameters:
    port: ttyUSB0
    baud_rate: 115200 # baud
    polling_interval: 12 # ms
    timeout_ms: 10 # ms
    restart_service_name: /restart_imu
    imu_publisher:
      topic_name: /sensors/primary/imu/raw
      frame_id: base_imu_link
      use_native_orientation: false
      measurements:
        acceleration:
          enabled: true
          covariance: [0.01425, 0.0, 0.0, 0.0, 0.01139, 0.0, 0.0, 0.0, 0.01189]
        angular_velocity:
          enabled: true
          covariance: [1e-09, 0.0, 0.0, 0.0, 1e-09, 0.0, 0.0, 0.0, 1e-09]
        orientation:
          enabled: true
          covariance: [0.00317, 0.0, 0.0, 0.0, 0.00312, 0.0, 0.0, 0.0, 0.17256]
    temperature_publisher:
      enabled: true
      topic_name: /temperature
      frame_id: base_link
      from_message: magnetometer # acceleration, angular_vel, orientation, magnetometer
      variance: 0.12181
      coefficient: 1.0 # Linear calibration parameters: coefficient
      addition: 0.0 # and addendum
    magnetometer_publisher:
      enabled: true
      topic_name: /magnetometer
      frame_id: compass
      coefficient: 0.00000001 # Linear calibration parameters: coefficient
      addition: 0.0 # and addendum
      covariance:
        [32.24426, 0.0, 0.0, 0.0, 32.87164, 0.0, 0.0, 0.0, 34.40223]
    orientation_publisher:
      enabled: true
      topic_name: /orientation
####################################################################
#
#        NOT USED BY HWT905
#
####################################################################
    gps_publisher:
      enabled: false
      navsat_fix_frame_id: world
      navsat_fix_topic_name: /gps
      navsat_altitude_topic_name: /gps_altitude
      navsat_satellites_topic_name: /gps_satellites
      navsat_variance_topic_name: /gps_variance
      ground_speed_topic_name: /gps_ground_speed
    rtc_publisher:
      enabled: false
      topic_name: /witmotion_clock
    barometer_publisher:
      enabled: false
      topic_name: /barometer
      frame_id: base_link
      variance: 0.001
      coefficient: 1.0 # Linear calibration parameters: coefficient
      addition: 0.0 # and addendum
    altimeter_publisher:
      enabled: false
      topic_name: /altitude
      coefficient: 1.0 # Linear calibration parameters: coefficient
      addition: 0.0 # and addendum
